-intstyle "ise" -incremental -o "C:/Users/Davinson/Downloads/Procesador1-master/testUniCtrl_isim_beh.exe" -prj "C:/Users/Davinson/Downloads/Procesador1-master/testUniCtrl_beh.prj" "work.testUniCtrl" 
